name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        emacs_version:
          - 27.1
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v2

    - name: Build
      run: cmake -S. -Bbuild -DCMAKE_CXX_FLAGS="-I/nix/var/nix/profiles/per-user/$USER/profile/include" && cmake --build build

    - name: Test
      run: |
        export LD_LIBRARY_PATH=$(nix eval --raw nixpkgs.stdenv.cc.cc.lib)/
        ls $LD_LIBRARY_PATH/
        cd build && ctest --output-on-failure
            
