name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Install Emacs
      run: |
        sudo add-apt-repository ppa:kelleyk/emacs
        sudo apt update
        sudo apt install emacs27

    - name: Install Gtk & poppler
      run: |
        sudo apt install libgtkmm-3.0-dev
        sudo apt install libpoppler-cpp-dev

    - uses: actions/checkout@v2

    - name: Build
      run: cmake -S. -Bbuild && cmake --build build

    - name: Test
      run: cd build && ctest --output-on-failure
            
